#fraction of attenuation due to diffuse interstellar medium
mu = 0
#dust effective optical depth
tau_V = 0
# gas recycling (no recycling if set to zero)
epsilon = 0
# number of tau values (charateristic scale for the SFH model) to generate
ntau = 69
# number of age values to generate
nage = 51
# Input photometric bands, separated by commas
bands = r,u,z,g,i
#lower and upper limit of the tau grid
tau_grid_lim = 0.04,13.8
#lower and upper limit of the age grid
age_grid_lim = 0.6,13.5
#The user defined redshift grid
nz_bin = 51
#The range of the redshift grid. Do not set the minimum to zero since it will raise a divide by zero error. 
z_grid_lim = 1e-4, 0.1
#The star formation history model. Only supports "SSP" (constant sfr), "tau" exponential model, "delayed" Delayed SFR as defined in Bruzual (1983), "custom" Custom sfh model. case sensitive
#The exponential model is more appropriate for elliptical galaxies since sfr should be small at late times. The delay model is more appropriate for spiral galaxies. 
sfh_model = custom
#The directories contains all the filters
filtdir = /home/u30/ylai2/FP_hydrosim_ML/pygalaxev/filters/
#The survey of the filters
survey = SDSS
#The directory of SSP
ssp_dir = "/home/u30/ylai2/FP_hydrosim_ML/pygalaxev/bc03/BaSeL3.1_Atlas/Chabrier_IMF/"
#Template name 
tempname = "lr_BaSeL"
#Work directory
work_dir = "/xdisk/timeifler/ylai2/output"
#File path for the SFH file if using custom sfh model
sfh_dir = "/xdisk/timeifler/ylai2/output"
#The path to the pygalaxev.py 
pygalaxev_path = "/home/u30/ylai2/FP_hydrosim_ML/pygalaxev"
#The number of custom sfh. Only needed this if you are using the custom sfh option for pygalaxev with the API option.
n_custom_sfh = 5

#The following are cosmological parameters of the illustris TNG simulation, only change these when using a different simulation. 
#The dark energy density
omega_lambda = 0.6911
#The matter density
omega_matter = 0.3089
#The baryon density
omega_b = 0.0486
#Sigma_8 
sigma_8 = 0.8159
#tilt of the primordial power spectrum
n_s = 0.9667
#Hubble parameter
h = 0.6774
#simulation
#simulation = TNG50-1
simulation = TNG100-1


#The following are the config for reading in the subhalos and particles from the illustris TNG, with API option 
n_galaxies = 30
#The snapshot should be between 0 and 99, snapshot 99 corresponds to redshift zero. 
snapshot = 99
#The output directory
out_dir = /xdisk/timeifler/ylai2/output/
#The directory of the supplementary catalogue. Leave it empty if not reading in supplementary files.
# supplementary_dir = /home/u30/ylai2/FP_hydrosim_ML/supplementary_catalogues/
supplementary_dir = 
#Your TNG API key
TNG_API_KEY = 955a6bbeb398daa9410dfeac1980e483
#The output mode. Only supports sfh or analysis, case sensitive. For sfh, it will calculate the sfh of n_galaxies and output them to the output directory as a text file. For analysis, you will need to have luminsoity grid pre-computed.
# mode = analysis
mode = sfh
#galaxev print statements verbose option. For debugging, set to 1, otherwise set to 0. 
verbose = 0
#How to load data. "API" means loading data from the TNG server while "local" means loading data from the downloaded TNG50 hdf5 files. Case sensitive. 
mode_load = local 
#Directory that contains the TNG50 hdf5 files 
# TNG_dir = /xdisk/timeifler/ylai2/TNG50/TNG50-1
TNG_dir = /xdisk/timeifler/ylai2/TNG100/TNG100-1
#Total number of hdf5 files of group catalogues in that snapshot. Only needed when mode_load is set to local
# num_catalog = 680 #For TNG50-1
num_catalog = 448 #For TNG100-1
#The number of hdf5 files to read in per job 
# index_per_job = 33 #TNG50-1
index_per_job = 12 #TNG100-1
#The log_10(sSFR) ridge defined in https://arxiv.org/abs/1707.05327
# sSFR_ridge = -0.93923837 #TNG50-1 simulation
sSFR_ridge = -0.9387605 #TNG100-1 simulation

#The file names of the supplementary_catalogues, sperated by commas to load multiple catalogues. Leave it empty if there is no supplementary files. 
#IMPORTANT: For a single file, you still need the comma at the end to tell python this is a list of string, otherwise it will just count the number of letter. 
sup_files = morphs_kinematic_bars.hdf5,

#The mass range of galaxies to be included. The TNG galaxies is generally in the range of 10^6 to 10^15 solar masses. 
mass_low = 1e9
# mass_high = 1e12
mass_high = 1e18 #For elliptical galaxy

#Minimum number of particles in the subhalo to be considered a galaxy
min_particles = 1000

#Number of histogram bins to calculate the SFH
n_sfh_bins = 45

#The default value for the following 2 parameters are taken from Xu et al, 2017. 1610.07605v2
#The number of grid cells per projected direction
n_grid_project = 100

#The region where the stellar particles are included (in terms of half-stellar-mass-radius). Default value taken from Xu et al 2017.
r_grid = 3

#The selection criteria 
#The selection criteria for subhalos before reading in the cutout data. The subhalos that does not satisfy the criteria will be skip and no cutout data will be load. 

#Whether to apply selection cut to subhalos. Enter 1 for applying selection cut, 0 for not applying cuts. 
sel_cut = 1
#What selection cut to apply. Only support 'ssfr' (specific star formation rate), 'Vmax_sigma'(ratio between maximum rotation velocity and velocity dispersion), or both
# sel_params = 'both'
sel_params = 'ssfr' #For elliptical galaxy
#This should be in Gyr^-1
ssfr_cut = 0.01
#This should be dimentionless
Vmax_disp_cut = 1.0
#Sersic index cut. For spiral galaxies, only select galaxies below the specified value. For elliptical galaxies, only select galaxies with sersic index bigger than the specified value. 
sersic_lim = 2
#Bands to simultaneously fit for the sersic index. The default follows Xu et al, 2017 to fit SDSS r, g, i bands. 
sersic_bands = r, g, i

# galaxy_type = 'spiral'
galaxy_type = 'elliptical'
#Line-of-sight axis (0=x, 1=y, 2=z)
los_axis = 2

#The range of velocity dispersion. Only include this for selecting elliptical galaxies within the range. Default is taken from Xu et al 2017. Currently not implemented. 
v_disp_range = 160, 400
#The portion of total kinetic energy is rotation, must be above the threshold to be considered a spiral galaxy. For elliptical galaxies, must be below this value. Default is taken from Yu-Hsiu's paper. 
kappa_lim = 0.5
#Maximum projected distance from the center to be considered inside the galaxy in kpc. The default value is taken from Xu et al 2017.
r_lim = 30
#The relative uncertainty in the surfacebrightness measurement error in dex. Default is 0.03 dex corresponds to 7% relative uncertainty. 
SB_sigma_sys = 0.03

#Diagnostic plots. Enter 1 for plotting these diagnostic plots or 0 to suppress the plotting. 
#plotting the velocity map
plot_vmap = 0
#Plotting the faceon, edgeon view of galaxies
plot_pos_view = 0
#Plotting the phase space diagram
plot_phase = 0
#The length range of the plot, plotting from -pos_lim to pos_lim
pos_lim_star = 5.0
pos_lim_gas = 10.0

#Combined hdf5 files in different folders into a single File if set to 1. Set to 0 if you are generating the HDF5 files. 
Combined_hdf5 = 0
#Whether to save the gas and star particle catalogues. Enter 1 if you want to save the particle catalogues, 0 otherwise. 
save_particles = 1